### ISSUE TITLE
pypylon library

### ISSUE THREAD

**Issue by Michelanjelo** [Lapland-UAS-Tequ/tequ-jetson-basler#1]
I have installed pypylon library to use camera with python API but importing pypylon is not recognized in jetson system root.
I need to autorun camera capturing and need it to executre in root. How can I know camera library in system root?

**Comment by juhaautioniemi** [comment]
Hello, I think better place for questions about Basler´s pypylon library installation and usage would be Basler official repository: https://github.com/basler/pypylon
